compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

enableTelemetry: false

nodeLinker: node-modules

npmMinimalAgeGate: 2d

supportedArchitectures:
  cpu:
    - x64
  os:
    - linux
    - win32
